#include <unistd.h> /* close */
#include <string.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <stdlib.h>
#include <stdio.h>

#define MAX_CLIENTS   2
#define EXIT_SEQ      "^["
#define MAX_SIZE      255

int main(int argc, const char * args[]) {

    struct sockaddr_in cli_1_addr, cli_2_addr;
    int srv_sock, cli_1_sock, cli_2_sock;
    int msg; // Recieve Message Status

    char cli_1_buff[1024] = {0};
    char cli_2_buff[1024] = {0};

    uint32_t cli_1_addr_len = sizeof(cli_1_addr);
    uint32_t cli_2_addr_len = sizeof(cli_2_addr);

    /* at this stage, there are no clients  */
    uint8_t no_clients = 1;
    uint8_t room_full = 0;
    uint8_t ctr_char_rcvd = 0;

    srv_sock = socket(AF_INET, SOCK_STREAM, 0);

    /*
     * Define messages generated by the server.
     */
    char welcome_msg[MAX_SIZE] = "Welcome to the chatroom that lives inside of your Terminal!\n"
                                  "Just type and press enter to send a message.\n"
                                  "^[ exits the chatroom session. \n \0";

    char solo_client_msg[MAX_SIZE] = "*** Waiting on a new client to join the chatroom... ***\n \0";

    char cli_exit_msg[MAX_SIZE] = "Other client left the chatroom. \n \0";

    char room_full_msg[MAX_SIZE] = "Room full! No other clients can join. Happy chatting! \n \0";

    while(1) {
        // If room is not full, then keep listening.
        if(listen(srv_sock, MAX_CLIENTS) == 0 && room_full == 0) {
            // accept first client and send welcome message
            if (no_clients) {

                cli_1_sock = accept(srv_sock, (struct sockaddr *) &cli_1_addr, &cli_1_addr_len);
                if(cli_1_sock > 0) {
                    write(cli_1_sock, welcome_msg, sizeof(welcome_msg));
                    read(cli_1_sock, cli_1_buff, sizeof(cli_1_buff));
		    write(cli_1_sock, solo_client_msg, sizeof(solo_client_msg));
		    no_clients = 0; // A client has officially joined the chatroom
		    ctr_char_rcvd = 1;
		    continue;
                } else {
		    //TODO: log.
		    continue;
		}
            } else {

                cli_2_sock = accept(srv_sock, (struct sockaddr *) &cli_2_addr, &cli_2_addr_len);

		        printf("accepting second cli");
                if(cli_2_sock > 0) {

                    send(cli_2_sock, welcome_msg, sizeof(welcome_msg), 0);
                    read(cli_2_sock, cli_2_buff, sizeof(cli_2_buff));
        		    write(cli_2_sock, room_full_msg, sizeof(room_full_msg));
        		    room_full = 1;
                } else {
                    //TODO: log.
                    continue;
                }
            }
        } else {
            //TODO: log.
    	    if(!room_full) {
                continue;
    	    }
        }
 
        bzero(cli_1_buff, sizeof(cli_1_buff));
        msg = read(cli_1_sock, cli_1_buff, sizeof(cli_1_buff));
        printf("sending %s\n", cli_1_buff);

        if(msg > 0) {
                if(ctr_char_rcvd == 1) {
        			ctr_char_rcvd = 0;
        			goto wait_on_recv;
                }
                write(cli_2_sock, cli_1_buff, sizeof(cli_1_buff));
		        printf("Msg sent!\n");
        } else {
	       //TODO: log.
	       continue;
        }

wait_on_recv:	
	    bzero(cli_2_buff, sizeof(cli_2_buff));
        msg = read(cli_2_sock, cli_2_buff, sizeof(cli_2_buff));
	    printf("sending %s\n", cli_2_buff);

        if(msg > 0) {

            if(strcmp(cli_2_buff, EXIT_SEQ) == 0) {

                close(cli_2_sock);
                send(cli_1_sock, cli_exit_msg, sizeof(cli_exit_msg), 0);
		room_full = 0;
            } else {
                write(cli_1_sock, cli_2_buff, sizeof(cli_2_buff));
		printf("Msg sent!\n");
            }
         } else {
           // TODO: log
	   continue;
         }
    }

    return 0; // Program shouldn't get here!
}
